### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Salvos** [Salvos/VS2016#1]
- [x] #3 - Upload verschönern :)
- [x] #9 - Mosaikgenerator gibt 0 response
- [ ] #12 - HSV-Diagramm fehlt komplett
- [x] #13 - Styling der Kachelgeneration schöner (farbinput, alles auf gleiche höhe, eventuell beschriftung...)
- [x] #14 - Kachelgeneration eventuell mit 3 auswahlwerten (von 0 bis 255 bei jeder Farbe - und alles was unter dem auswahlwert liegt wird generiert, sodass auch farbvariationen entstehen können)
- [ ] #16 - Löschen des Accounts soll auch die Informationen in der DB UND im Filesystem entfernen
- [x] #21 - Startseite mit Informationen füllen
- [x] #22 - read & writelock sinnvoll anpassen (ImageController ja!)

==Prio
#9, #13, #14, (#16), #21 #22

Dokumentation

=== zum schluss
- refactoring
- debugging entfernen
- doppelte funktionalitäten entfernen

**Comment by Salvos** [comment]
Erledigt:

- [x] #1 Beim erstellen eines Pools soll dieser gleich angezeigt werden (momentan über einen Button "Seite neu laden"
- [x] #2 - Pool ohne Namen erstellen = Exception
- [x] #4 - Tabellenspalten ordentlich benennen
- [x] #5 - Multiupload (?)
- [x] #6 - Motive umbennen geht nicht
- [x] #7 - Downloaden der Motive geht nicht
- [x] #8 - Löschen führt auf die Index zurück (sollte in den Pool)
- [x] #10 - Anzahl der Bilder im Pool stimmt noch nicht
- [x] #11 - Vorschaubild für Kacheln & Motive wäre schön :)
- [x] #15 - Auskommentieren (ImageController)
- [x] #17 - Löschen des Pools soll auch die Informationen in der DB UND im Filesystem entfernen
- [x] #18 - Löschen des Bildes soll auch die Informationen in der DB UND im Filesystem entfernen
- [x] #19 - Zugriff auf andere Pools sollte unterbunden sein
- [x] #20 - Zugriff auf andere Bilder sollte unterbunden sein
- [x] #23 - Bildernamen müssen Unique sein!
- [x] #24 - Bilderpfad ändern
